project:
  type: website

website:
  title: "PSCI 3200: Data and Development"
  navbar:
    left:
      - href: index.qmd
        text: Final Project
      - text: Past Assignments
        menu:
          - text: Preliminary Research Design
            href: Research_Design.qmd
          - text: Expanded Research Design
            href: expanded_research_design.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



